const express = require('express');
const axios = require('axios');
const Anthropic = require('@anthropic-ai/sdk');
const fs = require('fs').promises;
const path = require('path');
const sgMail = require('@sendgrid/mail');
require('dotenv').config();

const app = express();
app.use(express.json());

// Initialize SendGrid
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

// Initialize Anthropic (Claude)
const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({ status: 'healthy', service: 'PT Program Generator' });
});

// Main webhook endpoint from GHL
app.post('/webhook/generate-program', async (req, res) => {
  try {
    console.log('Received webhook:', JSON.stringify(req.body, null, 2));
    
    // Extract data from GHL webhook
    const { contactId, locationId, formData } = req.body;
    
    // Quick response to GHL
    res.status(200).json({ message: 'Program generation started' });
    
    // Process asynchronously
    await generateAndSendProgram(contactId, locationId, formData);
    
  } catch (error) {
    console.error('Webhook error:', error);
    res.status(500).json({ error: error.message });
  }
});

// Main program generation function
async function generateAndSendProgram(contactId, locationId, formData) {
  try {
    console.log(`Starting program generation for contact: ${contactId}`);
    
    // Step 1: Fetch contact data from GHL
    const contactData = await fetchGHLContact(contactId, locationId);
    console.log(`Fetched contact: ${contactData.name}`);
    
    // Step 2: Generate program with Claude AI
    const programContent = await generateProgramWithAI(contactData, formData);
    console.log('Program generated by AI');
    
    // Step 3: Create PDF from template
    const pdfBuffer = await generatePDF(contactData, programContent);
    console.log('PDF created');
    
    // Step 4: Email PDF to client
    await sendProgramEmail(contactData, pdfBuffer);
    console.log(`Program sent to: ${contactData.email}`);
    
    // Step 5: Upload PDF to GHL contact record (optional)
    // await uploadToGHL(contactId, locationId, pdfBuffer);
    
  } catch (error) {
    console.error('Program generation error:', error);
    // Send error notification
    await sendErrorNotification(error, contactId);
  }
}

// Fetch contact data from GHL
async function fetchGHLContact(contactId, locationId) {
  const apiKey = process.env.GHL_API_KEY;
  
  const response = await axios.get(
    `https://services.leadconnectorhq.com/contacts/${contactId}`,
    {
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Version': '2021-07-28'
      }
    }
  );
  
  const contact = response.data.contact;
  
  return {
    id: contact.id,
    name: contact.name || 'Client',
    firstName: contact.firstName || '',
    lastName: contact.lastName || '',
    email: contact.email,
    phone: contact.phone,
    customFields: contact.customField || {},
    tags: contact.tags || []
  };
}

// Generate program using Claude AI
async function generateProgramWithAI(contactData, formData) {
  const prompt = buildPrompt(contactData, formData);
  
  const message = await anthropic.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 4000,
    messages: [
      {
        role: 'user',
        content: prompt
      }
    ]
  });
  
  const responseText = message.content[0].text;
  
  // Parse the structured response
  // Expecting JSON format from Claude
  try {
    // Remove markdown code blocks if present
    let cleanedResponse = responseText.trim();
    
    // Check for markdown JSON code blocks and extract
    const jsonMatch = cleanedResponse.match(/```json\s*\n?([\s\S]*?)\n?```/);
    if (jsonMatch) {
      cleanedResponse = jsonMatch[1];
    } else {
      // Try to find just ``` code blocks
      const codeMatch = cleanedResponse.match(/```\s*\n?([\s\S]*?)\n?```/);
      if (codeMatch) {
        cleanedResponse = codeMatch[1];
      }
    }
    
    return JSON.parse(cleanedResponse.trim());
  } catch (e) {
    console.error('Failed to parse AI response as JSON:', e);
    // If not JSON, return as text with basic structure
    return { programText: responseText };
  }
}

// Build AI prompt
function buildPrompt(contactData, formData) {
  const {
    programGoal = 'general fitness',
    duration = '8',
    daysPerWeek = '4',
    experienceLevel = 'intermediate',
    equipment = 'full gym'
  } = formData || {};
  
  return `You are an expert personal trainer creating a customized training program.

CLIENT INFORMATION:
- Name: ${contactData.firstName} ${contactData.lastName}
- Experience Level: ${experienceLevel}
- Available Equipment: ${equipment}

PROGRAM REQUIREMENTS:
- Goal: ${programGoal}
- Duration: ${duration} weeks
- Training Days per Week: ${daysPerWeek}

Please generate a comprehensive training program in JSON format with the following structure:

{
  "programOverview": "Brief 2-3 sentence overview of the program approach",
  "weeks": [
    {
      "weekNumber": 1,
      "focus": "What this week emphasizes",
      "workouts": [
        {
          "day": 1,
          "title": "Workout name (e.g., Upper Body Strength)",
          "exercises": [
            {
              "name": "Exercise name",
              "sets": "3",
              "reps": "8-10",
              "rest": "90 seconds",
              "notes": "Form cues or modifications"
            }
          ]
        }
      ]
    }
  ],
  "progressionNotes": "How to progress week to week",
  "generalNotes": "Important reminders, warm-up guidance, cool-down"
}

Create a progressive, evidence-based program appropriate for their experience level. Include proper warm-up exercises and ensure balanced programming.

CRITICAL: Return ONLY valid JSON. Do not wrap in markdown code blocks. Do not include any text before or after the JSON. Just the raw JSON object.`;
}

// Generate PDF from HTML template
async function generatePDF(contactData, programContent) {
  // Load HTML template
  const templatePath = path.join(__dirname, 'templates', 'program-template.html');
  let htmlTemplate = await fs.readFile(templatePath, 'utf8');
  
  // Load and encode logo as base64
  const logoPath = path.join(__dirname, 'templates', 'logo.png');
  const logoBuffer = await fs.readFile(logoPath);
  const logoBase64 = logoBuffer.toString('base64');
  
  // Replace placeholders with actual data
  htmlTemplate = htmlTemplate
    .replace(/{{logoBase64}}/g, logoBase64)
    .replace(/{{programContent}}/g, formatProgramHTML(contactData, programContent));
  
  // Generate PDF using PDFShift API
  const response = await axios.post(
    'https://api.pdfshift.io/v3/convert/pdf',
    {
      source: htmlTemplate,
      landscape: false,
      use_print: false
    },
    {
      auth: {
        username: 'api',
        password: process.env.PDFSHIFT_API_KEY
      },
      responseType: 'arraybuffer'
    }
  );
  
  return Buffer.from(response.data);
}

// Format program content as HTML matching WCS Day 1 Program style
function formatProgramHTML(contactData, programContent) {
  if (!programContent.weeks) {
    return `<div class="program-text">${programContent.programText || 'Program content'}</div>`;
  }
  
  let html = '';
  
  // Page 1: Overview/Core Concepts
  html += `
    <div class="overview-page">
      <div class="page-header">
        <div class="header-left">
          <h1>WEST COAST STRENGTH</h1>
          <h2>TRAINING PROGRAM</h2>
        </div>
        <div class="header-right">
          <p>TRAINER: </p>
          <p>CLIENT: ${contactData.firstName} ${contactData.lastName}</p>
        </div>
      </div>
      
      <div class="core-concepts">
        <h3>CORE CONCEPTS:</h3>
        <div class="core-concepts-content">
          ${programContent.programOverview ? `<p>${programContent.programOverview}</p>` : ''}
          ${programContent.progressionNotes ? `<p><strong>Progression:</strong> ${programContent.progressionNotes}</p>` : ''}
          ${programContent.generalNotes ? `<p><strong>Important Notes:</strong> ${programContent.generalNotes}</p>` : ''}
        </div>
      </div>
    </div>
  `;
  
  // Generate workout pages - one page per workout
  programContent.weeks.forEach(week => {
    week.workouts.forEach(workout => {
      html += `
        <div class="workout-page">
          <div class="page-header">
            <div class="header-left">
              <h1>WEST COAST STRENGTH</h1>
              <h2>WEEK ${week.weekNumber} - DAY ${workout.day}</h2>
            </div>
            <div class="header-right">
              <p>TRAINER: </p>
              <p>CLIENT: ${contactData.firstName} ${contactData.lastName}</p>
            </div>
          </div>
          
          <table class="workout-table">
      `;
      
      // Add exercises as table rows
      workout.exercises.forEach(exercise => {
        const setsReps = `${exercise.sets} x ${exercise.reps}${exercise.rest ? ` | ${exercise.rest}` : ''}`;
        html += `
          <tr>
            <td>${exercise.name}</td>
            <td>${setsReps}</td>
          </tr>
        `;
      });
      
      html += `
          </table>
        </div>
      `;
    });
  });
  
  return html;
}

// Send program via email
async function sendProgramEmail(contactData, pdfBuffer) {
  const msg = {
    to: contactData.email,
    from: process.env.FROM_EMAIL || 'programs@westcoaststrength.com',
    subject: `Your Personalized Training Program - ${contactData.firstName}`,
    text: `Hi ${contactData.firstName},\n\nYour customized training program is attached. Please review it carefully and reach out if you have any questions.\n\nLet's crush these goals!\n\nWest Coast Strength Team`,
    html: `
      <p>Hi ${contactData.firstName},</p>
      <p>Your customized training program is attached. Please review it carefully and reach out if you have any questions.</p>
      <p><strong>Let's crush these goals!</strong></p>
      <p>West Coast Strength Team</p>
    `,
    attachments: [
      {
        content: pdfBuffer.toString('base64'),
        filename: `Training_Program_${contactData.firstName}_${contactData.lastName}.pdf`,
        type: 'application/pdf',
        disposition: 'attachment'
      }
    ]
  };
  
  await sgMail.send(msg);
}

// Send error notification
async function sendErrorNotification(error, contactId) {
  const msg = {
    to: process.env.ADMIN_EMAIL || 'justin@westcoaststrength.com',
    from: process.env.FROM_EMAIL || 'programs@westcoaststrength.com',
    subject: 'PT Program Generator Error',
    text: `Error generating program for contact ${contactId}:\n\n${error.message}\n\n${error.stack}`
  };
  
  try {
    await sgMail.send(msg);
  } catch (e) {
    console.error('Failed to send error notification:', e);
  }
}

// Start server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`PT Program Generator running on port ${PORT}`);
});
