const express = require('express');
const axios = require('axios');
const Anthropic = require('@anthropic-ai/sdk');
const puppeteer = require('puppeteer');
const fs = require('fs').promises;
const path = require('path');
const sgMail = require('@sendgrid/mail');
require('dotenv').config();

const app = express();
app.use(express.json());

// Initialize SendGrid
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

// Initialize Anthropic (Claude)
const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({ status: 'healthy', service: 'PT Program Generator' });
});

// Main webhook endpoint from GHL
app.post('/webhook/generate-program', async (req, res) => {
  try {
    console.log('Received webhook:', JSON.stringify(req.body, null, 2));
    
    // Extract data from GHL webhook
    const { contactId, locationId, formData } = req.body;
    
    // Quick response to GHL
    res.status(200).json({ message: 'Program generation started' });
    
    // Process asynchronously
    await generateAndSendProgram(contactId, locationId, formData);
    
  } catch (error) {
    console.error('Webhook error:', error);
    res.status(500).json({ error: error.message });
  }
});

// Main program generation function
async function generateAndSendProgram(contactId, locationId, formData) {
  try {
    console.log(`Starting program generation for contact: ${contactId}`);
    
    // Step 1: Fetch contact data from GHL
    const contactData = await fetchGHLContact(contactId, locationId);
    console.log(`Fetched contact: ${contactData.name}`);
    
    // Step 2: Generate program with Claude AI
    const programContent = await generateProgramWithAI(contactData, formData);
    console.log('Program generated by AI');
    
    // Step 3: Create PDF from template
    const pdfBuffer = await generatePDF(contactData, programContent);
    console.log('PDF created');
    
    // Step 4: Email PDF to client
    await sendProgramEmail(contactData, pdfBuffer);
    console.log(`Program sent to: ${contactData.email}`);
    
    // Step 5: Upload PDF to GHL contact record (optional)
    // await uploadToGHL(contactId, locationId, pdfBuffer);
    
  } catch (error) {
    console.error('Program generation error:', error);
    // Send error notification
    await sendErrorNotification(error, contactId);
  }
}

// Fetch contact data from GHL
async function fetchGHLContact(contactId, locationId) {
  const apiKey = process.env.GHL_API_KEY;
  
  const response = await axios.get(
    `https://services.leadconnectorhq.com/contacts/${contactId}`,
    {
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Version': '2021-07-28'
      }
    }
  );
  
  const contact = response.data.contact;
  
  return {
    id: contact.id,
    name: contact.name || 'Client',
    firstName: contact.firstName || '',
    lastName: contact.lastName || '',
    email: contact.email,
    phone: contact.phone,
    customFields: contact.customField || {},
    tags: contact.tags || []
  };
}

// Generate program using Claude AI
async function generateProgramWithAI(contactData, formData) {
  const prompt = buildPrompt(contactData, formData);
  
  const message = await anthropic.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 4000,
    messages: [
      {
        role: 'user',
        content: prompt
      }
    ]
  });
  
  const responseText = message.content[0].text;
  
  // Parse the structured response
  // Expecting JSON format from Claude
  try {
    return JSON.parse(responseText);
  } catch (e) {
    // If not JSON, return as text with basic structure
    return { programText: responseText };
  }
}

// Build AI prompt
function buildPrompt(contactData, formData) {
  const {
    programGoal = 'general fitness',
    duration = '8',
    daysPerWeek = '4',
    experienceLevel = 'intermediate',
    equipment = 'full gym'
  } = formData || {};
  
  return `You are an expert personal trainer creating a customized training program.

CLIENT INFORMATION:
- Name: ${contactData.firstName} ${contactData.lastName}
- Experience Level: ${experienceLevel}
- Available Equipment: ${equipment}

PROGRAM REQUIREMENTS:
- Goal: ${programGoal}
- Duration: ${duration} weeks
- Training Days per Week: ${daysPerWeek}

Please generate a comprehensive training program in JSON format with the following structure:

{
  "programOverview": "Brief 2-3 sentence overview of the program approach",
  "weeks": [
    {
      "weekNumber": 1,
      "focus": "What this week emphasizes",
      "workouts": [
        {
          "day": 1,
          "title": "Workout name (e.g., Upper Body Strength)",
          "exercises": [
            {
              "name": "Exercise name",
              "sets": "3",
              "reps": "8-10",
              "rest": "90 seconds",
              "notes": "Form cues or modifications"
            }
          ]
        }
      ]
    }
  ],
  "progressionNotes": "How to progress week to week",
  "generalNotes": "Important reminders, warm-up guidance, cool-down"
}

Create a progressive, evidence-based program appropriate for their experience level. Include proper warm-up exercises and ensure balanced programming.`;
}

// Generate PDF from HTML template
async function generatePDF(contactData, programContent) {
  // Load HTML template
  const templatePath = path.join(__dirname, 'templates', 'program-template.html');
  let htmlTemplate = await fs.readFile(templatePath, 'utf8');
  
  // Replace placeholders with actual data
  htmlTemplate = htmlTemplate
    .replace(/{{clientName}}/g, `${contactData.firstName} ${contactData.lastName}`)
    .replace(/{{currentDate}}/g, new Date().toLocaleDateString())
    .replace(/{{programContent}}/g, formatProgramHTML(programContent));
  
  // Launch headless browser and generate PDF
  const browser = await puppeteer.launch({
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
    headless: 'new'
  });
  
  const page = await browser.newPage();
  await page.setContent(htmlTemplate, { waitUntil: 'networkidle0' });
  
  const pdfBuffer = await page.pdf({
    format: 'A4',
    printBackground: true,
    margin: {
      top: '20px',
      right: '20px',
      bottom: '20px',
      left: '20px'
    }
  });
  
  await browser.close();
  
  return pdfBuffer;
}

// Format program content as HTML
function formatProgramHTML(programContent) {
  if (!programContent.weeks) {
    return `<div class="program-text">${programContent.programText || 'Program content'}</div>`;
  }
  
  let html = `<div class="program-overview">${programContent.programOverview}</div>`;
  
  programContent.weeks.forEach(week => {
    html += `
      <div class="week-section">
        <h2>Week ${week.weekNumber}</h2>
        <p class="week-focus"><strong>Focus:</strong> ${week.focus}</p>
    `;
    
    week.workouts.forEach(workout => {
      html += `
        <div class="workout">
          <h3>Day ${workout.day}: ${workout.title}</h3>
          <table class="exercise-table">
            <thead>
              <tr>
                <th>Exercise</th>
                <th>Sets</th>
                <th>Reps</th>
                <th>Rest</th>
                <th>Notes</th>
              </tr>
            </thead>
            <tbody>
      `;
      
      workout.exercises.forEach(exercise => {
        html += `
          <tr>
            <td>${exercise.name}</td>
            <td>${exercise.sets}</td>
            <td>${exercise.reps}</td>
            <td>${exercise.rest}</td>
            <td>${exercise.notes}</td>
          </tr>
        `;
      });
      
      html += `
            </tbody>
          </table>
        </div>
      `;
    });
    
    html += `</div>`;
  });
  
  if (programContent.progressionNotes) {
    html += `
      <div class="notes-section">
        <h3>Progression Notes</h3>
        <p>${programContent.progressionNotes}</p>
      </div>
    `;
  }
  
  if (programContent.generalNotes) {
    html += `
      <div class="notes-section">
        <h3>Important Notes</h3>
        <p>${programContent.generalNotes}</p>
      </div>
    `;
  }
  
  return html;
}

// Send program via email
async function sendProgramEmail(contactData, pdfBuffer) {
  const msg = {
    to: contactData.email,
    from: process.env.FROM_EMAIL || 'programs@westcoaststrength.com',
    subject: `Your Personalized Training Program - ${contactData.firstName}`,
    text: `Hi ${contactData.firstName},\n\nYour customized training program is attached. Please review it carefully and reach out if you have any questions.\n\nLet's crush these goals!\n\nWest Coast Strength Team`,
    html: `
      <p>Hi ${contactData.firstName},</p>
      <p>Your customized training program is attached. Please review it carefully and reach out if you have any questions.</p>
      <p><strong>Let's crush these goals!</strong></p>
      <p>West Coast Strength Team</p>
    `,
    attachments: [
      {
        content: pdfBuffer.toString('base64'),
        filename: `Training_Program_${contactData.firstName}_${contactData.lastName}.pdf`,
        type: 'application/pdf',
        disposition: 'attachment'
      }
    ]
  };
  
  await sgMail.send(msg);
}

// Send error notification
async function sendErrorNotification(error, contactId) {
  const msg = {
    to: process.env.ADMIN_EMAIL || 'justin@westcoaststrength.com',
    from: process.env.FROM_EMAIL || 'programs@westcoaststrength.com',
    subject: 'PT Program Generator Error',
    text: `Error generating program for contact ${contactId}:\n\n${error.message}\n\n${error.stack}`
  };
  
  try {
    await sgMail.send(msg);
  } catch (e) {
    console.error('Failed to send error notification:', e);
  }
}

// Start server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`PT Program Generator running on port ${PORT}`);
});
